---
name: Continuous Integration

on  :
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
        include:
          - os: ubuntu-latest
            CACHE_PIP: ~/.cache/pip
            CACHE_PRE_COMMIT: ~/.cache/pre-commit

    name: Lint
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.CACHE_PIP }}
            ${{ matrix.CACHE_PRE_COMMIT }}
          key: lint-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/.pre-commit-config.yaml')
            }}
          restore-keys: |
            lint-${{ runner.os }}-${{ matrix.python }}-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Lint
        run: |
          pre-commit run --all-files


  test-simple:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python: [3.9]
        include:
          - os: windows-latest
            CACHE_PIP: ~\AppData\Local\pip\Cache
            CACHE_POETRY: ~\AppData\Local\poetry\Cache
          - os: macos-latest
            CACHE_PIP: ~/Library/Caches/pip
            CACHE_POETRY: ~/Library/Caches/poetry

    name: Test (simple)
    runs-on: ${{ matrix.os }}
    needs: lint
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.CACHE_PIP }}
            ${{ matrix.CACHE_POETRY }}
          key: test-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml')
            }}
          restore-keys: |
            test-${{ runner.os }}-${{ matrix.python }}-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Collect Environment
        run: |
          echo "PYTHON=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
          echo "OS=$(python dev/os_version.py)" >> $GITHUB_ENV

      - name: Test
        run: |
          poetry run pytest -m "not docker" --verbose --numprocesses=auto --cov=src --cov-report=xml

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS, PYTHON

  test-full:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
        include:
          - os: ubuntu-latest
            CACHE_PIP: ~/.cache/pip
            CACHE_POETRY: ~/.cache/poetry

    name: Test (full)
    runs-on: ${{ matrix.os }}
    needs: lint
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    services:
      cmk:
        image: checkmk/check-mk-raw:2.1.0-latest
        env:
          CMK_PASSWORD: cmkadmin
        ports:
          - 8080:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.CACHE_PIP }}
            ${{ matrix.CACHE_POETRY }}
          key: test-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml')
            }}
          restore-keys: |
            test-${{ runner.os }}-${{ matrix.python }}-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Collect Environment
        run: |
          echo "PYTHON=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
          echo "OS=$(python dev/os_version.py)" >> $GITHUB_ENV

      - name: Test
        run: |
          poetry run pytest --verbose --numprocesses=auto --cov=src --cov-report=xml

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS, PYTHON

  docs:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
        include:
          - os: ubuntu-latest
            CACHE_PIP: ~/.cache/pip
            CACHE_POETRY: ~/.cache/poetry

    name: Documentation
    runs-on: ${{ matrix.os }}
    needs: [test-simple, test-full]
    permissions:
      contents: write

    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.CACHE_PIP }}
            ${{ matrix.CACHE_POETRY }}
          key: docs-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml')
            }}
          restore-keys: |
            docs-${{ runner.os }}-${{ matrix.python }}-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate Documentation
        run: |
          poetry run mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
